update workflows

diff --git a/.github/workflows/db-publish-workflow.yml b/.github/workflows/db-publish-workflow.yml
--- a/.github/workflows/db-publish-workflow.yml
+++ b/.github/workflows/db-publish-workflow.yml
@@ -37,14 +37,14 @@ jobs:
 
       - name: Build container for DB
         shell: bash
-        run: POSTGRES_DB=${{ secrets.DBNAME }} POSTGRES_USER=${{ secrets.DBUSER }} POSTGRES_PASSWORD=${{ secrets.DBPASS }} docker compose -f compose.yml up --detach
+        run: POSTGRES_DB=${{ secrets.DBNAME }} POSTGRES_USER=${{ secrets.DBUSER }} POSTGRES_PASSWORD=${{ secrets.DBPASS }} docker compose -f docker-ci-compose.yml up --detach
 
       - name: Verify that database is valid
         shell: bash
         run: |
           echo "Waiting for init scripts to complete"
           sleep 5
-          docker exec wander-db-test pg_isready -d ${{ secrets.DBNAME }} || { echo "::error unsuccessful container build with " && docker logs --tail 50 wander-db-test && exit 1; }
+          docker exec wander-db-test pg_isready -d ${{ secrets.DBNAME }} || { echo "::error unsuccessful container build with " && docker logs --tail 50 wander-db && exit 1; }
 
       - name: Pushing built image to Dockerhub
         shell: bash
