Added secrets to workflow

diff --git a/.github/workflows/db-workflow.yml b/.github/workflows/db-workflow.yml
--- a/.github/workflows/db-workflow.yml
+++ b/.github/workflows/db-workflow.yml
@@ -28,16 +28,17 @@ jobs:
       - name: Checkout repository to Github Workspace
         uses: actions/checkout@v3
 
-      - name: Image build
+      - name: Build container for DB
         shell: bash
         run: |
-          docker build -f Dockerfile -t wander/postgres-db .
+          POSTGRES_DB=${{ secrets.DBNAME }} 
+          POSTGRES_USER=${{ secrets.DBUSER }} 
+          POSTGRES_PASSWORD=${{ secrets.DBPASS }} 
+          docker compose -f compose.yml up
         
-
-      - name: Build and run container
+      - name: Verify that database is valid
         shell: bash
         run: |
-          docker run -d --name test-db wander/postgres-db
           echo "Waiting for init scripts to complete"
           sleep 5
-          docker exec test-db pg_isready -d wander-db || { echo "::error unsuccessful container build with " && docker logs --tail 50 test-db && exit 1; }
+          docker exec wander-db-test pg_isready -d ${{ secrets.DBNAME }} || { echo "::error unsuccessful container build with " && docker logs --tail 50 test-db && exit 1; }
