Change to container name for displaying logs

diff --git a/.github/workflows/db-workflow.yml b/.github/workflows/db-workflow.yml
--- a/.github/workflows/db-workflow.yml
+++ b/.github/workflows/db-workflow.yml
@@ -37,4 +37,4 @@ jobs:
         run: |
           echo "Waiting for init scripts to complete"
           sleep 5
-          docker exec wander-db-test pg_isready -d ${{ secrets.DBNAME }} || { echo "::error unsuccessful container build with " && docker logs --tail 50 test-db && exit 1; }
+          docker exec wander-db-test pg_isready -d ${{ secrets.DBNAME }} || { echo "::error unsuccessful container build with " && docker logs --tail 50 wander-db-test && exit 1; }
